package ridev.com.br.utils.errors;

public enum CustomErrors {
    ARENA(), MYSTERYBOX, ROLES, COMBATLOG, INVENTORY, KITS, LEADER, LOBBY, PERMISSIONS, RANK, UPDATER, USER, WARPS, WORLD, COMMANDS, EVENTS, LANGUAGE, DATABASE
}
